# Generated by Django 5.1.5 on 2025-01-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossaryentry',
            old_name='english_term',
            new_name='english_key',
        ),
        migrations.RenameField(
            model_name='glossaryentry',
            old_name='tetun_term',
            new_name='tetun_entry',
        ),
        migrations.RemoveField(
            model_name='glossaryentry',
            name='context',
        ),
    ]
