# Generated by Django 5.1.5 on 2025-01-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_rename_english_term_glossaryentry_english_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryentry',
            options={'verbose_name_plural': 'glossary entries'},
        ),
        migrations.AlterUniqueTogether(
            name='glossaryentry',
            unique_together={('english_key', 'tetun_entry')},
        ),
    ]
