# Generated by Django 5.1.5 on 2025-02-02 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_alter_glossaryentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpusentry',
            name='verified',
        ),
        migrations.AddField(
            model_name='corpusentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpusentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
