# Generated by Django 5.1.5 on 2025-02-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_remove_corpusentry_verified_corpusentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpusentry',
            options={'verbose_name_plural': 'corpus entries'},
        ),
        migrations.AlterUniqueTogether(
            name='corpusentry',
            unique_together={('english_text', 'tetun_text')},
        ),
    ]
