# Generated by Django 5.1.5 on 2025-02-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_alter_corpusentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_prompt', models.TextField(default='You are a linguist helping to post-edit translations from English to Tetun. Candidate translations are provided by Google Translate, and you are asked to correct them, if necessary, using examples and glossary entries. Only use examples and glossary entries to correct the translations.', help_text='System prompt used for the translation post-editing process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
