# Generated by Django 5.1.5 on 2025-02-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0007_systemconfiguration_post_editing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='translation_model',
            field=models.CharField(default='Google Translate', help_text="The model used for generating translations. Can be 'Google Translate', or a model from HuggingFace, e.g. 'Helsinki-NLP/opus-mt-en-tet'", max_length=100),
        ),
    ]
