# Generated by Django 5.1.5 on 2025-02-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0008_systemconfiguration_translation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='num_sentences_retrieved',
            field=models.IntegerField(default=5, help_text='The number of similar sentences retrieved for post-editing'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='translation_model',
            field=models.CharField(default='Google Translate', help_text="The model used for generating translations. Can be 'Google Translate', or a model from HuggingFace, e.g. 'Helsinki-NLP/opus-mt-en-tdt'", max_length=100),
        ),
    ]
