# Generated by Django 5.1.6 on 2025-02-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0009_systemconfiguration_num_sentences_retrieved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpusentry',
            old_name='tetun_text',
            new_name='translated_text',
        ),
        migrations.RenameField(
            model_name='glossaryentry',
            old_name='tetun_entry',
            new_name='translated_entry',
        ),
        migrations.AlterUniqueTogether(
            name='corpusentry',
            unique_together={('english_text', 'translated_text')},
        ),
        migrations.AlterUniqueTogether(
            name='glossaryentry',
            unique_together={('english_key', 'translated_entry')},
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='target_language_name',
            field=models.CharField(default='Tetun', max_length=100),
        ),
    ]
