# Generated by Django 5.1.6 on 2025-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0010_rename_tetun_text_corpusentry_translated_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='site_title',
            field=models.CharField(default='Medical English to Tetun Translation', max_length=100),
        ),
    ]
