# Generated by Django 5.1.6 on 2025-02-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0011_systemconfiguration_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='target_language_code',
            field=models.CharField(default='tet', help_text='ISO 639 language code, to be used in the Google Translate API', max_length=5),
        ),
    ]
