# Generated by Django 5.1.6 on 2025-03-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0012_systemconfiguration_target_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.TextField()),
                ('tgt', models.TextField()),
            ],
        ),
    ]
