# Generated by Django 5.1.6 on 2025-03-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0013_evalrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='placeholder',
            field=models.CharField(default='Stop the wound from bleeding, then do wound dressing.', help_text='Placeholder text for the translation input field', max_length=100),
        ),
    ]
