# Generated by Django 5.1.6 on 2025-03-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0014_systemconfiguration_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='dspy_config',
            field=models.JSONField(default=dict, help_text='Configuration for the dspy model'),
        ),
    ]
