# Generated by Django 5.1.6 on 2025-03-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0015_systemconfiguration_dspy_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='dspy_config',
            field=models.JSONField(default=dict, help_text='Optional: Configuration for the dspy model. If present, this takes precedence over the translation_prompt'),
        ),
    ]
