# Generated by Django 5.1.6 on 2025-03-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0016_alter_systemconfiguration_dspy_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='dspy_config',
            field=models.JSONField(blank=True, default=None, help_text='Optional: Configuration for the dspy model. If present, this takes precedence over the translation_prompt', null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='post_editing_model',
            field=models.CharField(default='gemini/gemini-2.0-flash', help_text='The model used for post-editing translations. Choose among https://docs.litellm.ai/docs/providers', max_length=100),
        ),
    ]
