# Generated by Django 5.1.6 on 2025-03-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0017_alter_systemconfiguration_dspy_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpusentry',
            options={'verbose_name': 'translation memory', 'verbose_name_plural': 'translation memories'},
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='login_required',
            field=models.BooleanField(default=True, help_text='Require users to log in to access the translation interface.'),
        ),
    ]
