# Generated by Django 5.1.6 on 2025-03-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0018_alter_corpusentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
